Nether:
  Members:
    - player1
    - player2
    - player3
  Coordinates:
    X: 115
    Y: 50
    Z: 53
End:
  Members:
    - player4
    - player5
  Coordinates:
    X: 0
    Y: 66
    Z: 0
Overworld:
  Members:
    - player6
    - player7
    - player8
  Coordinates:
    X: 0
    Y: 69
    Z: 0
